### ISSUE TITLE
Fix typo in russian version

### ISSUE THREAD

**Issue by MichaelAgarkov** [me-shaon/GLWTPL#102]
The Russian version says `УДАЧИ С ЭТОЙ ОБЩЕСТВЕННОЙ ЛИЦЕНЗИЕЙ`, which means `Good luck with that public license`, where it means good luck with the license itself.

Change it to `УДАЧИ С ЭТИМ ОБЩЕСТВЕННАЯ ЛИЦЕНЗИЯ` for it to be `Good luck with that public license` for it to say that it's the name of the license

**Comment by me-shaon** [comment]
Please make a PR for this change.

**Comment by MichaelAgarkov** [comment]
@me-shaon created it [here](https://github.com/me-shaon/GLWTPL/pull/103)
