### ISSUE TITLE
The profanity was funny

### ISSUE THREAD

**Issue by hppavilion1** [me-shaon/GLWTPL#15]
The license previously included several instances of the fuck word, which have since been removed. I can see people wanting to remove it, but I liked it; might I recommend two versions of the license, one with profanity and one without?

The GLWTSPL (Good Luck With That Shit Public License)?

**Comment by DaJuukes** [comment]
I support this motion, the profanity made the license what it was to begin with.

**Comment by jorgebucaran** [comment]
Can we meet in the middle and just add one profanity instance to the license?

**Comment by me-shaon** [comment]
[Happy](https://github.com/me-shaon/GLWTPL/blob/master/NSFW_LICENSE)?

**Comment by hppavilion1** [comment]
Yes.
