### ISSUE TITLE
"Buddha-like" Public License

### ISSUE THREAD

**Issue by amorist** [me-shaon/GLWTPL#24]
"Buddha-like" Public License

**Comment by me-shaon** [comment]
Please describe the issue.

**Comment by me-shaon** [comment]
@amorist I didn't get you yet. Could you please press some more keys to write some more words to describe what you are trying to say?

**Comment by the-j0k3r** [comment]
> @amorist I didn't get you yet. Could you please press some more keys to write some more words to describe what you are trying to say?

Good luck with that :)

**Comment by amorist** [comment]
just get start [Why-does-a-Buddha-like-youngster-become-a-popular-word-in-China-now-How-do-I-interpret-this-attitude-towards-life](https://www.quora.com/Why-does-a-Buddha-like-youngster-become-a-popular-word-in-China-now-How-do-I-interpret-this-attitude-towards-life)

GLWTPL like "Buddha-like" Public License

**Comment by amorist** [comment]
Good luck with that.

**Comment by amorist** [comment]
> When I wrote this, only God and I understood what I was doing.
Now, only God knows.
