### ISSUE TITLE
The first two paragraphs of the license should be swapped

### ISSUE THREAD

**Issue by me-shaon** [me-shaon/GLWTPL#40]
The following two paragraphs of the license should be swapped their places (as pointed by @thecsw in #39):

> The author has absolutely no clue what the code in this project does.
> It might just work or not, there is no third option.

> Everyone is permitted to copy, distribute, modify, merge, sell, publish,
> sublicense or whatever they want with this software but at their OWN RISK.

**Comment by DinoLeung** [comment]
Shell we start a new branch for this issue so contributors can start swapping their paragraph?

**Comment by DinoLeung** [comment]
We should reopen this issue until all translations are up to date

**Comment by me-shaon** [comment]
@DinoLeung I think it's not necessary to work on a separate branch. We can fix it on the main branch.

**Comment by me-shaon** [comment]
@DinoLeung AFAIK, any 'fixes' commit referencing this issue will automatically close this issue. Is there a way to override this behavior?

**Comment by DinoLeung** [comment]
With `Fixes` keyword, issue will close when pr merged into default branch. I believe merging into a separate branch might override this behaviour.
https://stackoverflow.com/a/15827689
