### ISSUE TITLE
Suggestion: add "Preamble" before the 3rd paragraph.

### ISSUE THREAD

**Issue by thecsw** [me-shaon/GLWTPL#49]
To make a sort of a good introduction and like real licenses, we can place the 3rd paragraph ("The author has absolutely no clue...") under `Preamble` section because right now it's just a paragraph that is not associated with copying, nor rules, so it should go under another section.

**Comment by DinoLeung** [comment]
agreed. 
might as well give a title like `Basic Permissions. ` to `0. ` under terms and conditions

**Comment by thecsw** [comment]
Yeah, right. I think this in no way complexes the license. It is small and understandable but it needs the "final touches" to be near perfect!

**Comment by me-shaon** [comment]
Could you please make a PR to show how it would actually be look like?

**Comment by DinoLeung** [comment]
in bd795cf I've make the format looks a bit more like GPL3.

**Comment by me-shaon** [comment]
Not that it matters but the spacing and alignment in your change look weird to me. :|

**Comment by DinoLeung** [comment]
ahh. what i've done was centre titles, and add two spaces before paragraphs. so i did a bit of re-format, and tried to limited each line to 75 characters

**Comment by me-shaon** [comment]
Yeah, I got that. But the [end result](https://github.com/me-shaon/GLWTPL/blob/bd795cf05600c1e90816367b74c9fdc08ce1bc60/LICENSE) looks weird. :/

**Comment by me-shaon** [comment]
Anyway, @DinoLeung Thanks for the suggestion. I'll try to see some other license formats and will try to make some formatting changes.

**Comment by DinoLeung** [comment]
yer, we might as well have a look at other license formats and see which one suit the most
