### ISSUE TITLE
remove or change [fullname] field 

### ISSUE THREAD

**Issue by pyrojkl** [me-shaon/GLWTPL#5]
[fullname] field in line 2 contradicts rule 0 ..."NEVER LEAVE A
TRACE TO TRACK THE AUTHOR"

**Comment by pyrojkl** [comment]
possible solution... I just thought of this:

`Copyright (c) [year] Only God Knows Who Wrote This`

**Comment by Alcaro** [comment]
Filling in the year rules out people who were born after, or died prior to, that date. Isn't that as a trace of who the author is?

**Comment by juju2143** [comment]
Unlike other licences where you have to give attribution to the original author no matter what you're doing with it, this could simply mean you'll have to remove any attribution or reference to the original author when you fork it, sell it or anything, maybe even replace it by your own, effectively stealing it.

The original author don't have to do anything as they have put the rules, they doesn't apply to them.

**Comment by me-shaon** [comment]
How about giving the copyright to 'Anonymous'?

**Comment by jswh** [comment]
How about 
> Copyright (c) [year] [The_World_God_Only_Knows](https://en.wikipedia.org/wiki/The_World_God_Only_Knows)

or even
> Copyright (c) [year] [Keima Katsuragi](https://en.wikipedia.org/wiki/List_of_The_World_God_Only_Knows_characters#Keima_Katsuragi)

**Comment by checkraiser** [comment]
Or change from Copyright to Copy&PasteRight ?

**Comment by abhiperry** [comment]
@jswh I hate myself for understanding your manga reference.

**Comment by xyproto** [comment]
If the author can be tracked by the style of writing code, will the license then revert to copyright, and to whom?
