### ISSUE TITLE
Add a list of contributors.

### ISSUE THREAD

**Issue by thecsw** [me-shaon/GLWTPL#50]
Currently, we have 27 contributors and I think it is important to somehow list them about what they did and how they contributed. For example, look at the bottom of README [here](https://github.com/MemeInvestor/memeinvestor_bot). A list of `Authors` where we can see them in their glory!

**Comment by me-shaon** [comment]
Can't. It would violate the terms of the license of this project.

**Comment by DinoLeung** [comment]
yer, contributors can be found [here](https://github.com/me-shaon/GLWTPL/graphs/contributors) anyway
