### ISSUE TITLE
Indentations

### ISSUE THREAD

**Issue by Yozhig** [me-shaon/GLWTPL#66]
License files have mixed indentations consist of tabs and spaces.

**Comment by thecsw** [comment]
Oh yeah, that's right. Looks messy

**Comment by me-shaon** [comment]
Is there any easy way to fix this? Cause, it'd be time-consuming to modify all of them. :/

**Comment by thecsw** [comment]
Okay, I used an emacs macro  where I could, should work just fine. I will make a pull request!

**Comment by me-shaon** [comment]
@thecsw any update on the PR? :)
