### ISSUE TITLE
submission to SPDX and OSI

### ISSUE THREAD

**Issue by 0cool-f** [me-shaon/GLWTPL#75]
Hi, i was thinking if you can submit this license for approval to the public list:
[SPDX List](https://spdx.org/licenses/)

The needed procedure is just to compile this:
[SPDX Validation Tool](http://13.57.134.254/app/submit_new_license/)

and eventually this:
[OSI Submission](https://opensource.org/approval)

What do you think about? o.O

**Comment by jaimergp** [comment]
https://spdx.org/licenses/GLWTPL.html
