### ISSUE TITLE
This license seems impossible to comply with

### ISSUE THREAD

**Issue by pleaserespond** [me-shaon/GLWTPL#80]
I have reservations about this part of the license:

"NEVER LEAVE A TRACE TO TRACK THE AUTHOR of the original product"

Given current ML techniques, it is possible to track down authors just by their coding style. Under these conditions, any users of the source code are under serious obligation to employ obfuscation techniques and scrub anything that might be deemed identifiable information. I feel like this clause should be changed to something more like "You must neither include links to where you got the code from, nor include the author's name, e-mail or other personal information, in either binary or source distributions".

**Comment by me-shaon** [comment]
https://gfycat.com/legitimateuncomfortablekookaburra

**Comment by me-shaon** [comment]
![LegitimateUncomfortableKookaburra-small](https://user-images.githubusercontent.com/831997/82746436-796a4000-9db1-11ea-8916-626d51b83743.gif)
