### ISSUE TITLE
Why not have a Badge?

### ISSUE THREAD

**Issue by catscarlet** [me-shaon/GLWTPL#86]
I think it will be cool, like this:

[![GLWTPL](https://img.shields.io/badge/GoodLuck-GLWT-red.svg)](https://github.com/me-shaon/GLWTPL)

Although I don't know which color or word is better.

[![GLWTPL](https://img.shields.io/badge/Good-Luck-red.svg)](https://github.com/me-shaon/GLWTPL)

[![GLWTPL](https://img.shields.io/badge/link-GLWT-blue.svg)](https://github.com/me-shaon/GLWTPL)

[![GLWTPL](https://img.shields.io/badge/Good_Luck_With_That-Public_License-information.svg)](https://github.com/me-shaon/GLWTPL)

You call.

**Comment by me-shaon** [comment]
That's a good idea. 
I think it'll be better.
[![GLWTPL](https://img.shields.io/badge/GLWT-Public_License-red.svg)](https://github.com/me-shaon/GLWTPL)

Can you please make a PR?

**Comment by tianyuanhao** [comment]
License badges usually look like these:

![](https://img.shields.io/github/license/jonas/tig)
![](https://img.shields.io/github/license/facebook/react)
![](https://img.shields.io/github/license/preservim/nerdtree)
![](https://img.shields.io/github/license/landley/toybox)

So I think we should use this badge:

![](https://img.shields.io/badge/license-GLWTPL-7cd958)

```
![](https://img.shields.io/badge/license-GLWTPL-7cd958)
```

See <https://github.com/badges/shields/blob/master/services/licenses.spec.js>.
