### ISSUE TITLE
Issue: There is no god

### ISSUE THREAD

**Issue by grimen** [me-shaon/GLWTPL#9]
So not even a god knows.

**Comment by me-shaon** [comment]
You should at least have someone to blame, right?

**Comment by sundflux** [comment]
I suggest replacing god with Aliens. They actually might exist, unlike imaginary bed-time story gods!

**Comment by me-shaon** [comment]
Let's not start a battle about God. I'm gonna close this.

**Comment by grimen** [comment]
![santa-claus-orig](https://user-images.githubusercontent.com/4783/41817017-c4565f1e-7760-11e8-97e5-16d36a15ee81.jpg)
